server:
  port: 9000

logging:
  level:
    aspire:
      demo: debug

    org:
      springframework:
        data: trace
    reactor:
      core: trace
      util: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"