server:
  port: 9000
logging.file: logs/learningspringboot.log
logging:
  level:
    aspire:
      demo: debug

    org:
      springframework:
        cloud: debug
        amqp: debug
        integration: debug
    reactor:
      core: trace
      util: trace
  file:
    max-size: 10MB


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
spring:
  devtools:
    remote:
      secret: learningspringboot
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-comment
          group: learning-spring-boot
        output:
          destination: learning-spring-boot-comment
          group: learning-spring-boot